### ISSUE TITLE
MSIE 11 returns 400 Invalid data

### ISSUE THREAD

**Issue by roflmao** [nature/boomcatch#59]
Mostly all of these useragents returns 400 invalid data. Is it possible do more debug on the data?

```
2015-06-04 15:12:27 INFO boomcatch: referer=http://www.xxxxxxx.no user-agent=Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko address=127.0.0.1[84.x.x.x] method=POST url=/beacon
2015-06-04 15:12:27 ERROR boomcatch: 400 Invalid data
```

```
# boomcatch --version
2.2.1
```

**Comment by philbooth** [comment]
Thanks for reporting this. As you're seeing, the error reporting sucks right now. I will definitely improve that soon.

In the meantime, I'll have a stab at reproducing then debugging this over the weekend. What command-line options are you running with?

Reason I ask is that 400 error is actually the result of a fairly high-level `catch` so a lot of things could be going wrong.

**Comment by roflmao** [comment]
```
cli.js --port 8080 --limit 100 --prefix abcrum. --fwdHost 192.168.30.113
```

Most POST's are faulty and all GET's are fine.
Is using the unmapped mapper a good way to start?

**Comment by philbooth** [comment]
I've reproduced this and have a stack-trace:

```
Error: Invalid number
    at assertImpl (/Users/phil.booth/Code/boomcatch/node_modules/check-types/src/check-types.js:600:19)
    at assertPredicate (/Users/phil.booth/Code/boomcatch/node_modules/check-types/src/check-types.js:595:9)
    at Object.positive (/Users/phil.booth/Code/boomcatch/node_modules/check-types/src/check-types.js:589:13)
    at normaliseRtData (/Users/phil.booth/Code/boomcatch/src/normalise.js:45:24)
    at normalise (/Users/phil.booth/Code/boomcatch/src/normalise.js:28:13)
    at map (/Users/phil.booth/Code/boomcatch/src/mappers/statsd.js:49:12)
    at send (/Users/phil.booth/Code/boomcatch/src/index.js:656:22)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:891:12)
```

Working on a fix now.

**Comment by philbooth** [comment]
Okay, this should be fixed in version 3.0.1. Let me know if you get any more problems.

**Comment by roflmao** [comment]
Upgraded to 3.0.1 and i get alot of these errors now:

```
TypeError: Cannot read property 'type' of undefined
    at /usr/lib/node_modules/boomcatch/src/mappers/statsd.js:73:21
    at Array.map (native)
    at mapRestimingMetrics (/usr/lib/node_modules/boomcatch/src/mappers/statsd.js:69:17)
    at /usr/lib/node_modules/boomcatch/src/mappers/statsd.js:61:23
    at Array.forEach (native)
    at map (/usr/lib/node_modules/boomcatch/src/mappers/statsd.js:51:23)
    at send (/usr/lib/node_modules/boomcatch/src/index.js:656:22)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```
Still running with the same options.

**Comment by philbooth** [comment]
Oh, sorry about that. Have raised #60 to cover it and am looking into it right now.
